[tools]
bun = "latest"

[tasks.validate]
description = "Validate the project"
run = "bun run lint && bun run format:check && bun run knip && bun run check"

[tasks.fix]
description = "Fix the project"
run = "bun run lint:fix && bun run format"
